import { IOrderItem } from '../types/order-items';

export function getOrderCatalog(): IOrderItem[] {
  return [
    // Classic

    {
      itemCode: 'SR',
      category: 'CS',
      subCategory: '01',
      pieces: ['01', '02'],
      isDouble: false,
      availableBrand: v => v !== 'FO' && v !== 'KA',
    },
    {
      itemCode: 'SV',
      category: 'CS',
      subCategory: '01',
      pieces: ['01', '02', '04'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'SP',
      category: 'CS',
      subCategory: '01',
      pieces: ['01', '02', '02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'SX',
      category: 'CS',
      subCategory: '01',
      pieces: ['01', '02', '02', '04'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'WR',
      category: 'CS',
      subCategory: '01',
      pieces: ['01', '02'],
      isDouble: true,
      availableBrand: v => true,
    },
    {
      itemCode: 'WV',
      category: 'CS',
      subCategory: '01',
      pieces: ['01', '02', '04'],
      isDouble: true,
      availableBrand: v => true,
    },
    {
      itemCode: 'WX',
      category: 'CS',
      subCategory: '01',
      pieces: ['01', '02', '02', '04'],
      isDouble: true,
      availableBrand: v => true,
    },
    {
      itemCode: 'WY',
      category: 'CS',
      subCategory: '01',
      pieces: ['01', '02', '02', '04'],
      isDouble: true,
      availableBrand: v => true,
    },
    {
      itemCode: 'S1',
      category: 'CS',
      subCategory: '01',
      pieces: ['01', '02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'S2',
      category: 'CS',
      subCategory: '01',
      pieces: ['01', '02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'BR',
      category: 'CS',
      subCategory: '02',
      pieces: ['01'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'BW',
      category: 'CS',
      subCategory: '02',
      pieces: ['01'],
      isDouble: true,
      availableBrand: v => true,
    },
    {
      itemCode: 'PR',
      category: 'CS',
      subCategory: '03',
      pieces: ['02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'P1',
      category: 'CS',
      subCategory: '03',
      pieces: ['02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'P2',
      category: 'CS',
      subCategory: '03',
      pieces: ['02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'VR',
      category: 'CS',
      subCategory: '04',
      pieces: ['04'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'PN',
      category: 'CS',
      subCategory: '03',
      pieces: ['02', '02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'BV',
      category: 'CS',
      subCategory: '02',
      pieces: ['01', '04'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'VS',
      category: 'CS',
      subCategory: '03',
      pieces: ['02', '04'],
      isDouble: false,
      availableBrand: v => true,
    },

    {
      itemCode: 'SR',
      category: 'MT',
      subCategory: '01',
      pieces: ['01', '02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'SV',
      category: 'MT',
      subCategory: '01',
      pieces: ['01', '02', '04'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'SP',
      category: 'MT',
      subCategory: '01',
      pieces: ['01', '02', '02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'SX',
      category: 'MT',
      subCategory: '01',
      pieces: ['01', '02', '02', '04'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'WR',
      category: 'MT',
      subCategory: '01',
      pieces: ['01', '02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'WV',
      category: 'MT',
      subCategory: '01',
      pieces: ['01', '02', '04'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'WX',
      category: 'MT',
      subCategory: '01',
      pieces: ['01', '02', '02', '04'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'WY',
      category: 'MT',
      subCategory: '01',
      pieces: ['01', '02', '02', '04'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'S1',
      category: 'MT',
      subCategory: '01',
      pieces: ['01', '02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'S2',
      category: 'MT',
      subCategory: '01',
      pieces: ['01', '02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'BR',
      category: 'MT',
      subCategory: '02',
      pieces: ['01'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'BW',
      category: 'MT',
      subCategory: '02',
      pieces: ['01'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'PR',
      category: 'MT',
      subCategory: '03',
      pieces: ['02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'P1',
      category: 'MT',
      subCategory: '03',
      pieces: ['02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'P2',
      category: 'MT',
      subCategory: '03',
      pieces: ['02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'VR',
      category: 'MT',
      subCategory: '04',
      pieces: ['04'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'PN',
      category: 'MT',
      subCategory: '03',
      pieces: ['02', '02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'BV',
      category: 'MT',
      subCategory: '02',
      pieces: ['01', '04'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'VS',
      category: 'MT',
      subCategory: '03',
      pieces: ['02', '04'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'FB',
      category: 'FM',
      subCategory: '01',
      pieces: ['01', '02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'FR',
      category: 'FM',
      subCategory: '01',
      pieces: ['01', '02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'FV',
      category: 'FM',
      subCategory: '01',
      pieces: ['01', '02', '04'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'FP',
      category: 'FM',
      subCategory: '01',
      pieces: ['01', '02', '02', '04'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'FZ',
      category: 'FM',
      subCategory: '01',
      pieces: ['01', '02', '02', '04'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'FQ',
      category: 'FM',
      subCategory: '01',
      pieces: ['01', '02', '02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'FW',
      category: 'FM',
      subCategory: '01',
      pieces: ['01', '02', '04'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'FY',
      category: 'FM',
      subCategory: '01',
      pieces: ['01', '02', '02', '04'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'FJ',
      category: 'FM',
      subCategory: '02',
      pieces: ['01'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'BF',
      category: 'FM',
      subCategory: '02',
      pieces: ['01'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'FI',
      category: 'FM',
      subCategory: '03',
      pieces: ['02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'VF',
      category: 'FM',
      subCategory: '04',
      pieces: ['04'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'FX',
      category: 'TX',
      subCategory: '07',
      pieces: ['01', '02'],
      isDouble: false,
      availableBrand: v => true,
    },

    {
      itemCode: 'XV',
      category: 'TX',
      subCategory: '07',
      pieces: ['01', '02', '04'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'WF',
      category: 'TX',
      subCategory: '07',
      pieces: ['01', '02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'WS',
      category: 'TX',
      subCategory: '07',
      pieces: ['01', '02', '04'],
      isDouble: false,
      availableBrand: v => true,
    },

    {
      itemCode: 'SR',
      category: 'WM',
      subCategory: '08',
      pieces: ['01', '02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'S5',
      category: 'WM',
      subCategory: '09',
      pieces: ['01', '05'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'SP',
      category: 'WM',
      subCategory: '08',
      pieces: ['01', '02', '02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'S6',
      category: 'WM',
      subCategory: '09',
      pieces: ['01', '05', '05'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'S7',
      category: 'WM',
      subCategory: '08',
      pieces: ['01', '02', '04'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'BR',
      category: 'WM',
      subCategory: '02',
      pieces: ['01'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'PR',
      category: 'WM',
      subCategory: '10',
      pieces: ['02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'SK',
      category: 'WM',
      subCategory: '11',
      pieces: ['05'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'PN',
      category: 'WM',
      subCategory: '10',
      pieces: ['02', '02'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'NS',
      category: 'WM',
      subCategory: '11',
      pieces: ['05', '05'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'OP',
      category: 'WM',
      subCategory: '13',
      pieces: ['10'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'O2',
      category: 'WM',
      subCategory: '14',
      pieces: ['01', '10'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'O7',
      category: 'WM',
      subCategory: '14',
      pieces: ['01', '02', '10'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'O6',
      category: 'WM',
      subCategory: '14',
      pieces: ['01', '05', '10'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'OR',
      category: 'WM',
      subCategory: '13',
      pieces: ['02', '10'],
      isDouble: false,
      availableBrand: v => true,
    },

    {
      itemCode: 'HD',
      category: 'DS',
      subCategory: '15',
      pieces: ['09'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'HH',
      category: 'DS',
      subCategory: '16',
      pieces: ['09'],
      isDouble: false,
      availableBrand: v => true,
    },
    {
      itemCode: 'HF',
      category: 'DS',
      subCategory: '17',
      pieces: ['09'],
      isDouble: false,
      availableBrand: v => true,
    },
  ];
}
